### ISSUE TITLE
Will you get drops from this too?

### ISSUE THREAD

**Issue by MissingNerd** [ucarno/ow-league-tokens#10]
Talking about this:
https://overwatchleague.com/en-us/2022/playoffs?playoffs=perks
Not sure how the app works so I'm asking to be sure

**Comment by bettydots** [comment]
same issue. i turned on the stream just in case. can we get an update when/if this is fixed? they must have changed how it worked because now the stream has that icon to enable drops or whatever

**Comment by scorthyn** [comment]
You dont need to do anything other than connect battle net account to youtube then it will say "connected" under the video  with a diamond icon

**Comment by fruzont** [comment]
> Talking about this: https://overwatchleague.com/en-us/2022/playoffs?playoffs=perks Not sure how the app works so I'm asking to be sure

Also curious about this

**Comment by ucarno** [comment]
Not sure about this, but I hope they left everything as is. Anyway, I will check their API and stuff when everything begins and do a quick fix if needed (and possible at all).

**Comment by fruzont** [comment]
Can 

> Not sure about this, but I hope they left everything as is. Anyway, I will check their API and stuff when everything begins and do a quick fix if needed (and possible at all).

Can I leave the stream open in my browser too just in case or would that break it?

**Comment by ucarno** [comment]
> Can I leave the stream open in my browser too just in case or would that break it?

Yes, you can

**Comment by scorthyn** [comment]
Will this be updated for tomorrows streams? Its gonna be the biggest drops ever with 13h watching in total for a bunch of skins. Thanks

**Comment by ucarno** [comment]
> I will check their API and stuff when everything begins and do a quick fix if needed (and possible at all).

**Comment by scorthyn** [comment]
Seems to be working the same, owl and ow channel both streaming. Only owl channel gives points as far as i know since it says "connected" status with my bn account. Btw when it says "time successfully tracked" does it mean my account is receiving\working properly? I added cookie number since automatic adding does not work.

**Comment by fruzont** [comment]
I got drops for my first hour of having the bot on, however it now says that the stream is offline while it isn't.

**Comment by scorthyn** [comment]
> I got drops for my first hour of having the bot on, however it now says that the stream is offline while it isn't.

Same here

**Comment by AndhikaWB** [comment]
I just tested and it also doesn't work for me. Stream is reported as not live and I need to add account ID manually. I didn't test it earlier so I don't know about the first hour drop, but I also opened YouTube just in case.

**Comment by Slightlyxz** [comment]
I also only received drops for the first hour, but unlike everyone else the stream says its live for me, dont have any problems regarding that.

**Comment by Slightlyxz** [comment]
Just checked ingame, got skin drops now. So it seems to work, guess you can close this.

**Comment by BadChocMilk** [comment]
> Just checked ingame, got skin drops now. So it seems to work, guess you can close this.
> 
> Edit: confirmed with friends, all 4 of us got the 3h rewards, 3 of them w/o having the YT stream open.

I thought that we won't receive any drops until the 15th? I have the program running 24/7 and I seemed to have only gotten token drops but no skins. Unless they were added and I just have not noticed them...?

**Comment by Slightlyxz** [comment]
> > Just checked ingame, got skin drops now. So it seems to work, guess you can close this.
> > Edit: confirmed with friends, all 4 of us got the 3h rewards, 3 of them w/o having the YT stream open.
> 
> I thought that we won't receive any drops until the 15th? I have the program running 24/7 and I seemed to have only gotten token drops but no skins. Unless they were added and I just have not noticed them...?
> 
> EDIT: Okay, just checked the skins from the op's link and yeah, I got the skins for the first 3 hours, but don't have the ones yet for hours 6+, guessing those will drop a bit later? not sure.

Got the mercy skin as well, just seems like they take a bit to roll out but so far I got upto 6h rewards.

**Comment by BadChocMilk** [comment]
I just checked this morning and I have the wrecking ball skin so it seems I now have up to12hrs. I'm assuming that the listed "additional drops" are whats to come on the 15th (considering that i do not have any of the sprays or player icons when checked), like stated on the page. You're right, I think this issue can be closed.
