### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by guidokl** [ucarno/ow-league-tokens#11]
Is this safe, or is there a risk to get an account ban from blizzard?

**Comment by ucarno** [comment]
Bot sends same requests to farm tokens as browser does when you watch league streams on official league website, but technically, it is possible to detect it.

Personally, I don't think Blizzard will ever care about it and invest people time and money into detecting 0.00001% of bot viewers.

If you are really afraid of ban, use bot from a different IP than you log in to battle.net, then Blizzard would have no way to know who is farming tokens, you or other person who knows your username.
