### ISSUE TITLE
sometime it say not live even if there is a live

### ISSUE THREAD

**Issue by Nicolo2524** [ucarno/ow-league-tokens#12]

**Comment by scorthyn** [comment]
Seems to be working now, I don't know if there's some different channels that this script doesnt take in consideration ?  Next week is gonna be big since its halloween and they will give u a bunch of skins if you watch for 30h overall

**Comment by ucarno** [comment]
I'll look into this next week
https://github.com/ucarno/ow-league-tokens/issues/10
