### ISSUE TITLE
Error when trying to open in nomenu mode on RPi

### ISSUE THREAD

**Issue by Spongled** [ucarno/ow-league-tokens#14]
![image](https://user-images.githubusercontent.com/27869072/197355925-e8cc6da4-0c88-4d6d-b867-2c38866efc61.png)

Any obvious ways I can rectify this? Unsure if it's a bug or an issue on my end.

**Comment by Spongled** [comment]
Nevermind - ran using python instead of python3, and seems to be working!

**Comment by Ubaldo-Santos** [comment]
Same error here. Also from raspberry. Executing  in 

python v3 <

` File "main.py", line 22
    def start_bot(earn_owl: bool, earn_owc: bool, account_ids: list[int]):
                                       ^
SyntaxError: invalid syntax`

python v3 > 

`Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from farmer import Farmer
  File "/home/pi/owl/ow-league-tokens-1.2.0/farmer.py", line 23, in <module>
    class Farmer:
  File "/home/pi/owl/ow-league-tokens-1.2.0/farmer.py", line 26, in Farmer
    check_if_live: bool = False, check_sentinel: bool = False
TypeError: 'type' object is not subscriptable`

**Comment by ucarno** [comment]
@Ubaldo-Santos try upgrading Python to version 3.9 or higher
