### ISSUE TITLE
Getting this error / not able to run 

### ISSUE THREAD

**Issue by ra1yuga** [ucarno/ow-league-tokens#16]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from farmer import Farmer
  File "/home/runner/OWL/farmer.py", line 23, in <module>
    class Farmer:
  File "/home/runner/OWL/farmer.py", line 25, in Farmer
    self, prefix: str, check_url: str, track_url: str, account_ids: list[int],
TypeError: 'type' object is not subscriptable
 
KeyboardInterrupt

![image](https://user-images.githubusercontent.com/87146226/198887781-d6b76769-8c2b-437c-86ce-07a697e88ed7.png)

Please help 
tried both python3.8 and python3.9

**Comment by tumGER** [comment]
Use Python v3.10, your Python versions are too old
