### ISSUE TITLE
Saying Stream is not live

### ISSUE THREAD

**Issue by Barry-Bot1** [ucarno/ow-league-tokens#17]
The bot says that the stream is not live, when it is live on YouTube

**Comment by Nicolo2524** [comment]
same

**Comment by ra1yuga** [comment]
same.. it was working 5 mins ago showing the status as live but now says not live

will have to keep youtube open on my phone tonight ig

**Comment by Nicolo2524** [comment]
this sucks

**Comment by viladit** [comment]
Yeah… it showed “live” only once :( omnic perks doesn’t work either

**Comment by ra1yuga** [comment]
since all we have to do after connecting blizzard account with youtube is : Watch the livestream 

wouldn't a simple script to watch youtube livesteams automatically work for this?

**Comment by Geckers** [comment]
it looks like its working now

**Comment by Nicolo2524** [comment]
it does not give double point too, or is just me? it should be double point https://overwatchleague.com/en-us/viewership-rewards-guide look at this

**Comment by Nicolo2524** [comment]
why they put a 2x if there is no 2x

**Comment by ucarno** [comment]
I will check the differences between data when bot thinks that stream is live and when it thinks it is not and then make a fix. Probably after next stream.

But it could be quickier if someone sends me an owl homepage (https://overwatchleague.com/en-us) 
HTML source next time bot says that stream is offline when it actually is live.

**Comment by Nicolo2524** [comment]
@ucarno there is no problem in your bot but the OW site at random just stop streaming the youtube live so the bot don't work, you should make the bot see the youtube page of overwatch league instead of the site.

**Comment by AndhikaWB** [comment]
There is a [similar tool](https://github.com/lilith645/Overwatch-League-Token-Scripts/blob/main/CheckChannelLive.py) which check YouTube live directly instead of using OWL site. The XPath selector is outdated but can be updated easily by using inspect element (refer to [#2](https://github.com/lilith645/Overwatch-League-Token-Scripts/issues/2)).

It uses Selenium though (not lightweight), I noticed that ucarno's program use something else.

**Comment by tired9494** [comment]
the problem with checking YouTube live is that it might not track all encores correctly as some of them are premieres instead of streams

**Comment by Nicolo2524** [comment]
@tired9494 better than not receiving token for a 30min because of ow league homepage bug

**Comment by Nicolo2524** [comment]
also right now they are making a rerun does the rerun give token?

**Comment by tired9494** [comment]
@Nicolo2524 it's detecting it as live but I'm getting errors with it sending tracking requests. Not sure if it's related

**Comment by tired9494** [comment]
> @tired9494 better than not receiving token for a 30min because of ow league homepage bug

well we don't know if the issue is being caused by the bot or the owl site rn

**Comment by ra1yuga** [comment]
> @Nicolo2524 it's detecting it as live but I'm getting errors with it sending tracking requests. Not sure if it's related

its live for me and also successfully sending tracking requests .. ig then premiers count too
![image](https://user-images.githubusercontent.com/87146226/199037294-38f1f919-90ab-491b-891e-b5b723c9ab82.png)

**Comment by LaurynasV97** [comment]
> also right now they are making a rerun does the rerun give token?

Encores give tokens.

**Comment by AndhikaWB** [comment]
> But it could be quickier if someone sends me an owl homepage (https://overwatchleague.com/en-us) HTML source next time bot says that stream is offline when it actually is live.

I can't retrieve the HTML source correctly, seems like there's a protection against it (the page will be blank/broken if saved). Using web archive also returned an error, sorry.

**Comment by Nicolo2524** [comment]
they made an update to the mobile app maybe they have fixed the random disconnect on the official homepage of the ow league but only time will tell

**Comment by ra1yuga** [comment]
can someone please confirm if this works for the 30 skins drop or not ? i did receive 60 League tokens by now but no skins

**Comment by LaurynasV97** [comment]
> can someone please confirm if this works for the 30 skins drop or not ? i did receive 60 League tokens by now but no skins

The FAQ says skins will be given out around November 15th.

**Comment by hazedj** [comment]
Wait why mine is doing fine is this normal?

**Comment by AetherCloud** [comment]
I'm constantly getting this error, and not I'm not getting any tokens in game.
![image](https://user-images.githubusercontent.com/40563409/199326899-ac872288-2460-4994-a0c8-e5d95324eefa.png)

**Comment by LaurynasV97** [comment]
> I'm constantly getting this error, and not I'm not getting any tokens in game. ![image](https://user-images.githubusercontent.com/40563409/199326899-ac872288-2460-4994-a0c8-e5d95324eefa.png)

Tokens can take up to 48 hours to be in your account. Also, the "not live" thing worried me too, but if you look to the left in the parentheses it says "OWC". That is for the contenders channel which hasn't streamed in months. Before you start the program, you can disable "contenders" drops and you won't see the message anymore.

**Comment by ucarno** [comment]
> I'm constantly getting this error
Only thing I can see from this screenshot is that contenders stream is offline (lines starting with OWC).

If you are not getting any tokens (for a long time), though bot is running, check if you have correct account set up:
1. Get your account ID by following steps from here: https://github.com/ucarno/ow-league-tokens#manually-getting-your-account-id
2. Compare it with value from `config.json` file (located in bot folder)

![Screenshot_1](https://user-images.githubusercontent.com/32498097/199332448-0dca054f-8fb9-4546-a394-b1fe44bd840c.png)

**Comment by hazedj** [comment]
The account ID is 9 digits right? or am I doing it wrong

**Comment by Nakda** [comment]
I received some tokens, and even the three first league skins (genji, etc) so I wouldn't worry. The rest will be distributed until Nov 15th I guess.

The only issue I have in my logs, after several hours of the docker container running, is an error regarding a promise which failed when Updating stream status for OWL, but it doesn't crash the process. Other than that, I checked the uptime by looking at the status updates (Now Live, Now Not Live) and it's pretty high so it's fine.
