### ISSUE TITLE
Incorrect token count

### ISSUE THREAD

**Issue by CaptainBoggle** [ucarno/ow-league-tokens#18]
App says 20 tokens, however upon logging in, I only have 5 tokens in my account.

**Comment by viladit** [comment]
I got only 5 too

**Comment by fruzont** [comment]
This is an issue on blizzard's side as many people have reported that they haven't got their tokens.

**Comment by ucarno** [comment]
Duplicate https://github.com/ucarno/ow-league-tokens/issues/10
