### ISSUE TITLE
Didn't get the tokens

### ISSUE THREAD

**Issue by bettydots** [ucarno/ow-league-tokens#19]
Had both the stream and the app open the whole duration of the stream and I only got 10 tokens

EDIT: checking some twitter comments and it might be an issue for everyone regardless of the app but posting here just in case

**Comment by Slightlyxz** [comment]
We had this happen a couple months back as well. 
I got drops from the first hour and after nothing, even with the stream running.

Seems like blizzard once again fucked up something on their side

**Comment by darkyng** [comment]
I've got nothing either, 
but they states: "Overwatch League tokens can take up to 48 hours to be granted to an account. Once granted, tokens will appear in the Overwatch League section of the Overwatch lobby." 

i'll report later as i've only used the bot.

**Comment by fruzont** [comment]
Same here, [it appears to be like this for everyone.](https://www.reddit.com/r/OverwatchLeague/comments/yhvqoc/hours_not_counting/)

**Comment by ucarno** [comment]
Duplicate https://github.com/ucarno/ow-league-tokens/issues/10
