### ISSUE TITLE
KeyError: 'uid'

### ISSUE THREAD

**Issue by Hinkiii** [ucarno/ow-league-tokens#24]
```
future: <Task finished name='Task-6' coro=<Farmer.update_data() done, defined at farmer.py:112> exception=KeyError('uid')>
Traceback (most recent call last):
  File "farmer.py", line 119, in update_data
KeyError: 'uid'
```
Had been working fine for days now

**Comment by BadChocMilk** [comment]
Yeah, happening to me too. Though it does say that its still successfully getting time tracked so I dunno if this is more of a proper issue, or if its just a silly annoyance. Guess we shall see in some time once tokens are dropped out for people. Oh and btw, do encore streams also award tokens if you watch the stream the first time around? Haven't been able to find a good answer online about it.

**Comment by tired9494** [comment]
you'll get bonus tokens on encores regardless of whether or not you watched the original stream

**Comment by BadChocMilk** [comment]
> you'll get bonus tokens on encores regardless of whether or not you watched the original stream

Awesome, tysm! I thought so but I very unsure about it, glad to have confirmation.
