### ISSUE TITLE
Suggestion support for encore VODs

### ISSUE THREAD

**Issue by MrHugelberg** [ucarno/ow-league-tokens#26]
hi, just found this token farmer. Amazing stuff, thanks for your work.
I have a suggestion to make or rather a question

Would it be possible to check for encore premieres? Usually they do encores the day after wich drop tokens as well.

**Comment by vnagrand** [comment]
> hi, just found this token farmer. Amazing stuff, thanks for your work. I have a suggestion to make or rather a question
> 
> Would it be possible to check for encore premieres? Usually they do encores the day after wich drop tokens as well.

It checks encores.

**Comment by MrHugelberg** [comment]
whoops, sorry 
I should've checked myself. my bad
