### ISSUE TITLE
Raspberry Pi docker install?

### ISSUE THREAD

**Issue by austin283874** [ucarno/ow-league-tokens#27]
Im new to this so bear with me if this is a dumb question, but I'm trying to get this to run on my raspberry pi 3b+. I tried: docker run probablypablito/ow-league-tokens but returned this error:
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

Is this just due to arm being different than x86 or am I missing something to get this to run on a pi?

**Comment by Nakda** [comment]
Yes, if I remember correctly the architecture for which the project is built is not ARM. Since I have a Pi 4, I had to build the project targeting ARM64.

**Comment by aftrmth728** [comment]
> Yes, if I remember correctly the architecture for which the project is built is not ARM. Since I have a Pi 4, I had to build the project targeting ARM64.

Would it be possible to show me your docker-compose.yml? I haven't received any tokens since setting it up on Tuesday and I'm wanting to check I didn't make an error when editing the compose file.

Thanks

**Comment by Nakda** [comment]
Sure, here it is:
[docker-arm64.yml.txt](https://github.com/ucarno/ow-league-tokens/files/9940110/docker-arm64.yml.txt)

**Comment by Adrii-dll** [comment]
Im on a Pi 3 and no errors for me, i just followed the instructions

**Comment by austin283874** [comment]
Yeah it turned out when I reset my pi I used the 32bit image rather than the 64 bit raspbian image. Now I am just being a noob with docker and trying to find a directory to edit docker-compose.yml
