### ISSUE TITLE
Dockerize?

### ISSUE THREAD

**Issue by probablypablito** [ucarno/ow-league-tokens#3]
I don't know if you're willing to do this, but it would be super useful

**Comment by probablypablito** [comment]
I kinda did it myself by hardcoding my account id into the Dockerfile. It's not ideal and it should be a value that could be set in the environment variables but it works ¯\_(ツ)_/¯

I attached the Dockerfile below if anyone wants it. Just put it in the same directory as main.py, edit the id(s) in the file, and do `sudo docker build -t ow-league-tokens .` Then run it with `sudo docker run ow-league-tokens`


Remember to remove the txt extension from the file!
[Dockerfile.txt](https://github.com/ucarno/ow-league-tokens/files/9086813/Dockerfile.txt)

**Comment by probablypablito** [comment]
Made a pull request with proper support

**Comment by ucarno** [comment]
Merged!
