### ISSUE TITLE
Launch and run on startup?

### ISSUE THREAD

**Issue by Crashkila101** [ucarno/ow-league-tokens#31]
If there's not an option already, could this app be run on startup, maybe even in the system tray? I know I can place a shortcut in my startup apps but, obviously, that wouldn't have the script running, just the process executing.

**Comment by ucarno** [comment]
You can start this app without menu using provided `Start_Without_Menu.bat` script. I think you can just make a shortcut of a script and put it in your startup folder located in `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup`
