### ISSUE TITLE
Not getting any OWL tokens

### ISSUE THREAD

**Issue by MagixGames** [ucarno/ow-league-tokens#34]
I've been using this for about 3 weeks, using the ID method, and have had it up for pretty much all OWL streams as of late. Yet, I've gotten no tokens, even though those streams say that they give tokens.

Might just be a dumb me thing but is there any reason?

**Comment by catalpaaa** [comment]
bruh owl ended like back in nov. 4th

**Comment by MagixGames** [comment]
they still host streams that say they give tokens

**Comment by catalpaaa** [comment]
> they still host streams that say they give tokens

If ur talking about the challenger cup the I don't think it gives you any tokens

**Comment by MrHugelberg** [comment]
> they still host streams that say they give tokens

AFAIK only the final stream of challengers cup gave tokens. Unfortunately it can be totally on Blizzard side cause their whole drop thing is so buggy that I can take months to receive your stuff.
