### ISSUE TITLE
Bot doesn't detect stream being live

### ISSUE THREAD

**Issue by azenia** [ucarno/ow-league-tokens#37]
Stream is currently live, but bot program says it's offline? Not sure if it's due it being on Twitch instead of Youtube though.

![image](https://user-images.githubusercontent.com/77856893/224565404-85b69d45-cdd6-4e96-b7e7-2d268898fe3b.png)
Also side question being: does it work when closed or you do need to have the terminal open all the time (and i assume it'd be best to have this in shell startup then?)

**Comment by ucarno** [comment]
Bot only detects streams that are on overwatchleague.com website.
If you want Twitch drops, you could try this app: https://github.com/DevilXD/TwitchDropsMiner

And yes, bot can only work if terminal window is open.

**Comment by azenia** [comment]
![image](https://user-images.githubusercontent.com/77856893/235323170-e9a77abd-090e-4b87-aa15-aa6580cd6561.png)
This should be working right? or I don't understand why it doesnt.
