### ISSUE TITLE
Overwatch League Pro-Am Cup - Could Not Get Player Data

### ISSUE THREAD

**Issue by dcao3** [ucarno/ow-league-tokens#38]
![image](https://user-images.githubusercontent.com/12177637/227337565-a95273c1-2386-4273-8471-03653f465824.png)

Confirmed correct ID too.

![image](https://user-images.githubusercontent.com/12177637/227337913-47868e9e-fe57-443b-8868-d96912012a63.png)

**Comment by MrHugelberg** [comment]
Not entirely sure if this is basically the same error, but mine throws errors too

`
[2023-03-23 20:11:02,565 - ERROR] Task exception was never retrieved
future: <Task finished name='Task-61495' coro=<Farmer.update_data() done, defined at /app/farmer.py:112> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/app/farmer.py", line 116, in update_data
    data_player = [i['videoPlayer'] for i in data['props']['pageProps']['blocks'] if 'videoPlayer' in i][0]
IndexError: list index out of range
`

**Comment by Sergo1217** [comment]
same error
![image](https://user-images.githubusercontent.com/16447886/227345348-118d1ca9-5d9e-4491-bc9c-b75f0f4abce1.png)

**Comment by ucarno** [comment]
"Could not get player data" (player where you watch the video, not person) occurs because OWL site literally has no player - if you click on "LIVE" at the top you will see this page with 500 error instead of expected player:
![Screenshot_1](https://user-images.githubusercontent.com/32498097/227375842-f57e1ec9-a710-4b72-b002-2c6c05559194.png)

Strangely, contenders site works as expected.

**Comment by Aezriel82** [comment]
> "Could not get player data" (player where you watch the video, not person) occurs because OWL site literally has no player - if you click on "LIVE" at the top you will see this page with 500 error instead of expected player: ![Screenshot_1](https://user-images.githubusercontent.com/32498097/227375842-f57e1ec9-a710-4b72-b002-2c6c05559194.png)
> 
> Strangely, contenders site works as expected.

so does this error break the farmer or is it just a inconsequential error?

**Comment by dclstn** [comment]
![image](https://user-images.githubusercontent.com/43322006/227394392-973a6ab3-a460-44cb-8905-8a665c52c574.png)
By "Token Sweepstakes" they're dropping codes in chat instead, seems like a blunder on their part

**Comment by Aezriel82** [comment]
was hoping to test this and see if it still works... typical :)

**Comment by MrHugelberg** [comment]
OWL Opening weekend will give token drops again (starting from 27th May)

**Comment by MrHugelberg** [comment]
Do we know if it will work again next week or did they just changed the base how their tracking works?
Iirc they changed contenders to be youtube only (for drops) right

Well, I mean if theres not even a player on website anymore then I guess we're out of luck? (if thats the case next week as well)

**Comment by Aezriel82** [comment]
getting this error during first live game.. 
[2023-04-28 06:38:00,389 - INFO] (OWL) Updating stream status...
[2023-04-28 06:38:00,405 - INFO] (OWC) Updating stream status...
[2023-04-28 06:38:01,333 - INFO] (OWL) Could not get player data, keeping stream status as Offline.
[2023-04-28 06:38:01,536 - INFO] (OWC) Could not get player data, keeping stream status as Offline.

**Comment by ucarno** [comment]
> getting this error during first live game.. [2023-04-28 06:38:00,389 - INFO] (OWL) Updating stream status... [2023-04-28 06:38:00,405 - INFO] (OWC) Updating stream status... [2023-04-28 06:38:01,333 - INFO] (OWL) Could not get player data, keeping stream status as Offline. [2023-04-28 06:38:01,536 - INFO] (OWC) Could not get player data, keeping stream status as Offline.

Bot is not working because **OWL site has no stream**. I am currently rewriting it to YouTube instead.
