### ISSUE TITLE
Providing another way to find account_id

### ISSUE THREAD

**Issue by BreakshadowCN** [ucarno/ow-league-tokens#42]
That is, under %LOCALAPPDATA%\Blizzard Entertainment\Overwatch there are folders that are named by account_ids (these are account_ids for users who has logined into your PC's Battle.net before).
Find your account_id (ignore numbers below 199999 - these are Overwatch hotfixes sorted by their build ids) by their last modified time and fill your id/ids into OverwatchTokenFarmer.exe's menu.

For potential Chinese users: Ignore ids that are started with 5. These are ids for CN server only and will not work. If you are not a Chinese player, you can safely ignore this sentence.

**Comment by Aezriel82** [comment]
excuse my ignorance but whats a CN user? i have multiple numbers less than 199999 and only 1 other (that i thought was my ID) that is larger than that, but it DOES start with 5?

**Comment by ucarno** [comment]
Will consider adding this to Readme when IDs will be needed again, thanks!
