### ISSUE TITLE
Error: cannot connect to chrome at 127.0.0.1:port

### ISSUE THREAD

**Issue by catalpaaa** [ucarno/ow-league-tokens#45]
> Exception in thread Thread-2 (start_chrome):
> Traceback (most recent call last):
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/catalpa/nas/program/ow-league-tokens/src/app.py", line 33, in start_chrome
>     driver = uc.Chrome(
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
>     super(Chrome, self).__init__(
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
>     super().__init__(
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
>     super().__init__(
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 704, in start_session
>     super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
>     self.error_handler.check_response(response)
>   File "/home/catalpa/mambaforge/envs/owl/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:37609
> from chrome not reachable
> Stacktrace:
> #0 0x55672c11afe3 <unknown>
> #1 0x55672be59bc1 <unknown>
> #2 0x55672be47ff6 <unknown>
> #3 0x55672be86e00 <unknown>
> #4 0x55672be7e352 <unknown>
> #5 0x55672bec0af7 <unknown>
> #6 0x55672bec011f <unknown>
> #7 0x55672beb7693 <unknown>
> #8 0x55672be8a03a <unknown>
> #9 0x55672be8b17e <unknown>
> #10 0x55672c0dcdbd <unknown>
> #11 0x55672c0e0c6c <unknown>
> #12 0x55672c0ea4b0 <unknown>
> #13 0x55672c0e1d63 <unknown>
> #14 0x55672c0b4c35 <unknown>
> #15 0x55672c105138 <unknown>
> #16 0x55672c1052c7 <unknown>
> #17 0x55672c113093 <unknown>
> #18 0x7f423a494b43 <unknown>

boot with `python src/main.py --nomenu` on headless Ubuntu 22

**Comment by tired9494** [comment]
Did you end up fixing this? I'm trying to get this to work on ARM and I'm now running into this error

**Comment by catalpaaa** [comment]
> Did you end up fixing this? I'm trying to get this to work on ARM and I'm now running into this error

You cant run over ssh, or you have to let it open a chrome gui though ssh with DISPLAY=:0 python

**Comment by Th3Kolbask1n** [comment]
> > Did you end up fixing this? I'm trying to get this to work on ARM and I'm now running into this error
> 
> You cant run over ssh, or you have to let it open a chrome gui though ssh with DISPLAY=:0 python

I have the same problem on linux without display. Copied the profiles folder. But still can't connect. Вid you manage to fix the problem?
