### ISSUE TITLE
How do I use the app on Windows 10? 

### ISSUE THREAD

**Issue by LowHighh** [ucarno/ow-league-tokens#46]
idk how to download and use the app after the update,

**Comment by ucarno** [comment]
Wait for the executable. I will close this issue when it is ready.

**Comment by kavz2002** [comment]
![image](https://user-images.githubusercontent.com/132108621/235327187-8acc49a0-7264-4010-9613-a12ff8db931f.png)

**Comment by ucarno** [comment]
https://github.com/ucarno/ow-league-tokens/releases/latest
