### ISSUE TITLE
Bot not working anymore

### ISSUE THREAD

**Issue by Slightlyxz** [ucarno/ow-league-tokens#5]
Since this season it's not possible to get the ow contenders rewards through the owl site anymore, you are only able to get the rewards through youtube now. Found this on another farming tool: https://github.com/shirokumacode/overwatch-omnic-rewards/issues/28

Wouldn't be surprised if OWL will use this system in the future aswell.

**Comment by Slightlyxz** [comment]
Haven't gotten tokens for the last 2 days from OWL as well now, seems like they use the same system as in contenders now?

**Comment by Z0pyrus** [comment]
Same for me

**Comment by ucarno** [comment]
I saw no changes to the league tracking API during recent investigation, so there is nothing I can do on my side. Probably they have just messed up
https://github.com/shirokumacode/overwatch-omnic-rewards/issues/32

**Comment by Slightlyxz** [comment]
Tokens started being rolled out again. Contenders seems to still not work :/
Gonna close this anyway
