### ISSUE TITLE
Proxy/Tor

### ISSUE THREAD

**Issue by github59173** [ucarno/ow-league-tokens#6]
Proxy all requests and responses by account to hide large account lists from being tracked down to one ip address.
Use of public/private proxy list and/or Tor would also work. I know it's a stretch to assume blizzard cares enough to ban stuff like this but it would help.

**Comment by snessim** [comment]
If Blizzard decided to care, wit would likely block earning via known TOR nodes and proxies

**Comment by ucarno** [comment]
Too late for now, I'll maybe prepare an update for next year
