### ISSUE TITLE
Command for close all tabs

### ISSUE THREAD

**Issue by brusvv** [ucarno/ow-league-tokens#64]
Can you add the command close all opened tabs via app? Also would be nice if you can a feature, which can turn off PC when stream is inactive or inactive more than N minutes.

**Comment by ucarno** [comment]
> Can you add the command close all opened tabs via app?
What tabs do you want to close? Можешь ответить по-русски.

> feature, which can turn off PC
This feature will be added later

**Comment by brusvv** [comment]
> > Can you add the command close all opened tabs via app?
> 
> What tabs do you want to close? Можешь ответить по-русски.
> Окна Хрома, то я 13-15 акков запускаю и даже через Ctrl+W долго закрывать.
Микрофича, но было бы еще классно, если бы можно было выбирать какие аккаунты запускать для фарма, хотя бы через консоль.

**Comment by ucarno** [comment]
Все окна можно закрыть через комбинацию клавиш `Ctrl + C` (в консоли). Если закрывать через крестик, то функция очистки не выполняется.
