### ISSUE TITLE
Startup problem without GUI

### ISSUE THREAD

**Issue by lettt3t** [ucarno/ow-league-tokens#67]
I'm trying to run it on a server without a GUI, I've created the profiles beforehand, but even so I get the same errors when using "headless".
https://github.com/ucarno/ow-league-tokens/issues/60

**Comment by lettt3t** [comment]
Message: unknown error: cannot connect to chrome at 127.0.0.1:43149
from chrome not reachable
Stacktrace:
#0 0x562f40247133 <unknown>
#1 0x562f3ff7b7f0 <unknown>
#2 0x562f3ff69656 <unknown>
#3 0x562f3ffa8f60 <unknown>
#4 0x562f3ffa0932 <unknown>
#5 0x562f3ffe09ad <unknown>
#6 0x562f3ffe018f <unknown>
#7 0x562f3ffd79a3 <unknown>
#8 0x562f3ffac46a <unknown>
#9 0x562f3ffad55e <unknown>
#10 0x562f40206cae <unknown>
#11 0x562f4020a8fe <unknown>
#12 0x562f40213f20 <unknown>
#13 0x562f4020b923 <unknown>
#14 0x562f401dec0e <unknown>
#15 0x562f4022eb08 <unknown>
#16 0x562f4022ec97 <unknown>
#17 0x562f4023f113 <unknown>
#18 0x7f383825c609 start_thread


Traceback (most recent call last):
  File "/home/vps/test1/src/app.py", line 310, in bootstrap
    start_chrome(config)
  File "/home/vps/test1/src/app.py", line 150, in start_chrome
    drivers.append(get_driver(profile, config))
  File "/home/vps/test1/src/app.py", line 104, in get_driver
    raise e
  File "/home/vps/test1/src/app.py", line 59, in get_driver
    driver = uc.Chrome(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 704, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:43149
from chrome not reachable
Stacktrace:
#0 0x562f40247133 <unknown>
#1 0x562f3ff7b7f0 <unknown>
#2 0x562f3ff69656 <unknown>
#3 0x562f3ffa8f60 <unknown>
#4 0x562f3ffa0932 <unknown>
#5 0x562f3ffe09ad <unknown>
#6 0x562f3ffe018f <unknown>
#7 0x562f3ffd79a3 <unknown>
#8 0x562f3ffac46a <unknown>
#9 0x562f3ffad55e <unknown>
#10 0x562f40206cae <unknown>
#11 0x562f4020a8fe <unknown>
#12 0x562f40213f20 <unknown>
#13 0x562f4020b923 <unknown>
#14 0x562f401dec0e <unknown>
#15 0x562f4022eb08 <unknown>
#16 0x562f4022ec97 <unknown>
#17 0x562f4023f113 <unknown>
#18 0x7f383825c609 start_thread

**Comment by ucarno** [comment]
Error is too broad, can't really help here. Have you tried adding `--headless` argument to `config.json` file: https://github.com/ucarno/ow-league-tokens/issues/60#issuecomment-1531449064 ?

**Comment by Th3Kolbask1n** [comment]
> Error is too broad, can't really help here. Have you tried adding `--headless` argument to `config.json` file: [#60 (comment)](https://github.com/ucarno/ow-league-tokens/issues/60#issuecomment-1531449064) ?

i have this problem again. nothing helps anymore

**Comment by lettt3t** [comment]
I tried to run differently. In the end, it didn't work. Having installed the xfce and vnc shell for remote access, after authorization in the browser, I already managed to launch it in console form. As I understand it, after the transfer of profiles, everything stops working.
----------------------------------------------------------------------------------
Я пытался по-разному запустить. По итогу, никак не получалось. Поставив оболочку xfce и vnc для удаленного доступа, после авторизации в браузере, у меня получилось запустить в консольном виде. Как понимаю, после переноса профилей, все перестает работать.

**Comment by Th3Kolbask1n** [comment]
> #### I tried to run differently. In the end, it didn't work. Having installed the xfce and vnc shell for remote access, after authorization in the browser, I already managed to launch it in console form. As I understand it, after the transfer of profiles, everything stops working.
> #### Я пытался по-разному запустить. По итогу, никак не получалось. Поставив оболочку xfce и vnc для удаленного доступа, после авторизации в браузере, у меня получилось запустить в консольном виде. Как понимаю, после переноса профилей, все перестает работать.

 Да, заметил, что первый раз она запускается и даже работает. Но при переносе профилей виснет

**Comment by ucarno** [comment]
Current "solution" is to install GUI and VNC into the GUI. Headless on Linux without a GUI will not be supported as it requires some tweaks, but I am willing to support it through Docker.

Contribute to/track this issue here: https://github.com/ucarno/ow-league-tokens/issues/63
