### ISSUE TITLE
2 Questions about how it works

### ISSUE THREAD

**Issue by AmrKhalid666** [ucarno/ow-league-tokens#69]
Hello. When I launch the bot and use it, it takes me to the stream on google chrome page, once I get the success message, is it safe to close the page?

Also, does it work with spring stage where there's no tokens but you get a few recolors for watching ~12hrs

**Comment by ucarno** [comment]
> is it safe to close the page

No, don't close it. If you don't want this window, try headless mode (you can turn it on in menu)

> does it work with spring stage

It watches all streams on OWL channel
