### ISSUE TITLE
Question: What task does this Application facilitate

### ISSUE THREAD

**Issue by AmrKhalid666** [ucarno/ow-league-tokens#70]
Hello. 

I highly appreciate the lightning quick response from last time, I was not present to add further onto my inquiry at the time.

I am not certain about the usefulness of this app. I was under the impression that it would be like the twitch drops miner app, where it sends a "1 minute watched" pulse to the servers to save you bandwidth, however reading further I realize that is not the case. What are some ways I can save time by using this app?

**Comment by ucarno** [comment]
1. Automation: set up and forget, streams can't be missed (especially if you have PC running 24/7 or you buy cheap VPS)
2. Easier to farm on multiple accounts

Just don't use it if you don't get value of it, that's it
