### ISSUE TITLE
Questions about rewards starting during the stream

### ISSUE THREAD

**Issue by asdf1280** [ucarno/ow-league-tokens#71]
I have noticed that when Blizzard starts the drops (a.k.a. Connected icon on the player) much after the stream starts from time to time. In this case, I don't get the drop without refreshing the page, if I have played the stream earlier than the drop. In such scenario, does this tool automatically refresh the stream page?

**Comment by ucarno** [comment]
Latest release of this tool (v2.0.3) refreshes stream every 15 minutes
