### ISSUE TITLE
Suggestion: auto detect chrome version

### ISSUE THREAD

**Issue by catalpaaa** [ucarno/ow-league-tokens#76]
[undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) always uses the latest chrome, this makes the bot fail to start when the version not match up.

**Comment by wangziyingwen** [comment]
It seems to have the code of automatic detection version, but the error is not successfully caught (except code not run)? 
I try to manually add the version information, it can be run.
